# Generated by Django 2.2 on 2019-12-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_pw',
            new_name='confirm',
        ),
    ]
