# Generated by Django 2.2 on 2019-12-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_auto_20191218_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm',
        ),
    ]
